version: "3.8"

services:
    react-app:
        container_name: basic-react-app
        build:
            context: ./fe
            dockerfile: Dockerfile
            target: ${APP_ENV}
            args:
                NEXT_PUBLIC_API_URL: ${API_URL}
                NEXT_PUBLIC_SITE_ID: ${NEXT_PUBLIC_SITE_ID}
                NEXT_PUBLIC_MAINT_NAME: ${NEXT_PUBLIC_MAINT_NAME}
                NEXT_PUBLIC_ENCRYPTION_KEY: ${NEXT_PUBLIC_ENCRYPTION_KEY}
        restart: always
        ports:
            - "${REACT_EXPOSE_PORT}:${REACT_CONTAINER_PORT}"
        volumes:
            - basic_fe_node_modules:/app/node_modules
        environment:
            - NODE_ENV=${APP_ENV}
            - TZ=Asia/Seoul
        env_file:
            - ./.env
        networks:
            - basic_net
        command: >
            sh -c "
              if [ \"$APP_ENV\" = \"production\" ]; then
                node .next/standalone/server.js;
              else
                npm run dev;
              fi"

    node-app:
        container_name: basic-node-app
        build:
            context: ./be
            dockerfile: Dockerfile
            target: ${APP_ENV}
        restart: always
        ports:
            - "${NODE_EXPOSE_PORT}:${NODE_CONTAINER_PORT}"
        volumes:
            - ./be:/app
            - basic_be_node_modules:/app/node_modules
        environment:
            - TZ=Asia/Seoul
            - NODE_ENV=${APP_ENV}
        env_file:
            - ./.env
        networks:
            - basic_net

volumes:
    basic_fe_node_modules:
    basic_be_node_modules:

networks:
    basic_net:
        driver: bridge
