version: "3.8"

services:
    # Next.js 프론트엔드 (개발환경)
    react-app:
        container_name: aphennet-nextjs-dev
        build:
            context: ./fe
            dockerfile: Dockerfile
            target: development
            args:
                NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-https://api.aphen.net}
                NEXT_PUBLIC_SITE_ID: ${NEXT_PUBLIC_SITE_ID:-aphennet}
                NEXT_PUBLIC_MAINT_NAME: ${NEXT_PUBLIC_MAINT_NAME:-Aphennet}
                NEXT_PUBLIC_ENCRYPTION_KEY: ${NEXT_PUBLIC_ENCRYPTION_KEY:-LnsSEX1tg3A3OMD4/qdtbapFwF3abNfA84xUJ2M/1mw=}
        restart: always
        ports:
            - "${REACT_EXPOSE_PORT:-3000}:3000"
        volumes:
            - ./fe/src:/app/src
            - ./fe/public:/app/public
            - ./fe/next.config.js:/app/next.config.js
            - ./fe/tailwind.config.js:/app/tailwind.config.js
            - ./fe/postcss.config.js:/app/postcss.config.js
            - ./fe/tsconfig.json:/app/tsconfig.json
            - ./fe/components.json:/app/components.json
        environment:
            - NODE_ENV=development
            - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-https://api.aphen.net}
            - TZ=Asia/Seoul
        env_file:
            - ./.env 
        networks:
            - aphennet-network

    # Node.js 백엔드 (개발환경) - 운영 DB 사용
    node-app:
        container_name: aphennet-nodejs-dev
        build:
            context: ./be
            dockerfile: Dockerfile
            target: development
        restart: always
        ports:
            - "${NODE_EXPOSE_PORT:-3001}:3000"
        volumes:
            - ./be/src:/app/src
            - ./be/app.js:/app/app.js
            - ./be/nodemon.json:/app/nodemon.json
            - ./be/swagger.yaml:/app/swagger.yaml
            - ./be/package.json:/app/package.json
            - ./be/package-lock.json:/app/package-lock.json
            - ./be/upload:/app/upload
        environment:
            - NODE_ENV=development
            - TZ=Asia/Seoul
        env_file:
            - ./.env
        networks:
            - aphennet-network
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s

volumes:
    nextjs_node_modules:
    nodejs_node_modules:
    upload_data:

networks:
    aphennet-network:
